// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/heytom-labs/heytom-gateway/internal/config"
	"github.com/heytom-labs/heytom-gateway/internal/registry"
	"github.com/heytom-labs/heytom-gateway/internal/server/grpc"
	"github.com/heytom-labs/heytom-gateway/internal/server/http"
)

// InitializeApp 初始化应用程序
func InitializeApp() (*App, error) {
	cfg := config.ProvideConfig()
	reg, err := registry.ProvideRegistry(cfg)
	if err != nil {
		return nil, err
	}
	httpServer := http.ProvideServer(cfg)
	grpcServer := grpc.ProvideServer(cfg, reg)

	app := &App{
		Config:     cfg,
		HTTPServer: httpServer,
		GRPCServer: grpcServer,
		Registry:   reg,
	}

	return app, nil
}
