// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/heytom-labs/heytom-gateway/internal/config"
	"github.com/heytom-labs/heytom-gateway/internal/registry"
	"github.com/heytom-labs/heytom-gateway/internal/server/grpc"
	"github.com/heytom-labs/heytom-gateway/internal/server/http"
)

import (
	_ "github.com/heytom-labs/heytom-gateway/internal/registry/consul"
)

// Injectors from wire.go:

// InitializeApp 初始化应用程序
func InitializeApp() (*App, error) {
	configConfig := config.ProvideConfig()
	registryRegistry, err := registry.ProvideRegistry(configConfig)
	if err != nil {
		return nil, err
	}
	httpProxy, err := http.ProvideHTTPProxy(configConfig, registryRegistry)
	if err != nil {
		return nil, err
	}
	server := http.ProvideServer(configConfig, httpProxy)
	grpcServer := grpc.ProvideServer(configConfig, registryRegistry)
	app := &App{
		Config:     configConfig,
		HTTPServer: server,
		GRPCServer: grpcServer,
		Registry:   registryRegistry,
	}
	return app, nil
}
